# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2ray.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'v2ray.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bv2ray.proto\x12\"v2ray.core.app.router.routercommon\"\xab\x02\n\x06\x44omain\x12=\n\x04type\x18\x01 \x01(\x0e\x32/.v2ray.core.app.router.routercommon.Domain.Type\x12\r\n\x05value\x18\x02 \x01(\t\x12G\n\tattribute\x18\x03 \x03(\x0b\x32\x34.v2ray.core.app.router.routercommon.Domain.Attribute\x1aR\n\tAttribute\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x03H\x00\x42\r\n\x0btyped_value\"6\n\x04Type\x12\t\n\x05Plain\x10\x00\x12\t\n\x05Regex\x10\x01\x12\x0e\n\nRootDomain\x10\x02\x12\x08\n\x04\x46ull\x10\x03\"[\n\x07GeoSite\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12:\n\x06\x64omain\x18\x02 \x03(\x0b\x32*.v2ray.core.app.router.routercommon.Domain\"I\n\x0bGeoSiteList\x12:\n\x05\x65ntry\x18\x01 \x03(\x0b\x32+.v2ray.core.app.router.routercommon.GeoSiteb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2ray_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOMAIN']._serialized_start=52
  _globals['_DOMAIN']._serialized_end=351
  _globals['_DOMAIN_ATTRIBUTE']._serialized_start=213
  _globals['_DOMAIN_ATTRIBUTE']._serialized_end=295
  _globals['_DOMAIN_TYPE']._serialized_start=297
  _globals['_DOMAIN_TYPE']._serialized_end=351
  _globals['_GEOSITE']._serialized_start=353
  _globals['_GEOSITE']._serialized_end=444
  _globals['_GEOSITELIST']._serialized_start=446
  _globals['_GEOSITELIST']._serialized_end=519
# @@protoc_insertion_point(module_scope)
